  const RUmine_url = "https://youtu.be/voH0S0e01vs?si=g38vWuUqhXVRTV82";
  const ForzaHorizon_playlsit_url = "https://www.youtube.com/watch?v=1RfeC8LtxPQ&list=PLCutjjq7vO82Aa2MbyO3A6_bKHEY-tS7j";
  const chaos_mark_cinematic = "https://youtu.be/dNFGJQIW5ZM?si=piHe5cnzak2GUaNH&t=118";
  const dmc_combichrist = "https://youtu.be/_9J8ccza1OI?si=auJSiHZwMEYIID7y&t=13";
  const lara_radio_climb = "https://youtu.be/8ULSAuYvu5Y?si=BVTZ37dWmAQIacrj&t=1066";
  const psp_splinter_cell_stealth = "https://youtu.be/6lhN3alxqHk?si=ZvtITXJNDB_otEUC&t=594";

  const gameMasterList = [
    {
      "name": "Dota 2",
      "tier": "SSS",
      "category": "",
      "platform": "PC",
      "played_year": 2012,
      "score": 99,
      "comment": "No comments.",
      "igdb_id": 2963,
      "rawg_id": 10213,
    },
    {
      "name": "Hollow Knight: Silksong",
      "tier": "SSS",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 98,
      "comment": `Perfect sequel for
      the best metroidvania,
      that excels in every aspect.`,
      "igdb_id": 115289,
      "rawg_id": 292844,
    },
    {
      "name": "Hollow Knight",
      "tier": "SSS",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2019,
      "score": 96,
      "comment": "Best metroidvania of it's time with combat depth and vast engaging world.",
      "igdb_id": 365702,
      "rawg_id": 9767,
    },
    {
      "name": "Indiana Jones and the Great Circle",
      "tier": "A",
      "category": "AAA",
      "platform": "Xbox Series X",
      "played_year": 2025,
      "score": 77,
      "comment": "Game that makes you feel like Indiana Jones. Polished first-person animations and micro-sandbox-levels here and there. Game is quite short, but it's a good thing - it focuses on what matters without filler content!",
      "igdb_id": 142415,
      "rawg_id": "indiana-jones-and-the-great-circle",
    },
    {
      "name": "Disc Room",
      "tier": "A",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 75,
      "comment": "Fast gameplay loop. Hardcode 2D micro-skill-demending game aboud dodging DISCS.",
      "igdb_id": 131614,
      "rawg_id": 513878,
    },
    {
      "name": "The Messenger",
      "tier": "A",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 80,
      "comment": "Clever commentary on a genre, disguised as a classic action platformer. Medium-challenge.",
      "igdb_id": 71628,
      "rawg_id": 302239,
    },
    {
      "name": "Level Devil",
      "tier": "S",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 90,
      "comment": "So creative with so little. Game messes with your expectations.",
      "igdb_id": 279687,
      "rawg_id": 1000161,
    },
    {
      "name": "Haste",
      "tier": "A",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 76,
      "comment": "3D-runner with unique satisfying locomotion mechanics and very polished animations. Not a fun of the plot though.",
      "igdb_id": 228918,
      "rawg_id": 719612,
    },
    {
      "name": "King is Watching",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 74,
      "comment": "3D-runner with unique satisfying locomotion mechanics and very polished animations. Not a fun of the plot though.",
      "igdb_id": 282826,
      "rawg_id": 1007234,
    },
    {
      "name": "Bridge Constructor Portal",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 68,
      "comment": "Satisfying portal-themed puzzles, Portal humor included",
      "igdb_id": 76770,
      "rawg_id": 50675,
    },
    {
      "name": "Detroit: Become Human",
      "tier": "SS",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2025,
      "score": 90,
      "comment": "As good as an interactive-movie kinda game can go. True story branching, main character can die midway through and the game goes on. Played as a local coop.",
      "igdb_id": 14362,
      "rawg_id": 29177,
    },
    {
      "name": "The Dark Pictures Anthology: Man of Medan",
      "tier": "C",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2025,
      "score": 62,
      "comment": "As a coop movie night thing it's pretty good. Classic Supermassive Games thing where characters try to avoid death and your choices  matter. But damn the plot is baaad :D",
      "igdb_id": 55047,
      "rawg_id": "man-of-medan",
    },
    {
      "name": "Super Meat Boy",
      "tier": "A",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 81,
      "comment": "Used to play it as a flash game, wanted to give it another try. Aaaand it's still super hard!",
      "igdb_id": 885,
      "rawg_id": "super-meat-boy",
    },
    {
      "name": "Lara Croft GO",
      "tier": "A",
      "category": "",
      "platform": "PC",
      "played_year": 2025,
      "score": 74,
      "comment": "Classic turn base 2D puzzle, great twists on mechanics, in-depth exploration of each mechanic and how it overlaps with others. Constantly gives you an a-ha moment.",
      "igdb_id": 11592,
      "rawg_id": 700,
    },
    {
      "name": "What Remains of Edith Finch",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2024,
      "score": 72,
      "comment": "Not as much of a game gameplay-wise, but a briliant showcase of how video game medium can be used as an engaging narrative tool. Magical realism at its finest.",
      "igdb_id": 11233,
      "rawg_id": "what-remains-of-edith-finch",
    },
    {
      "name": "SUPERHOT",
      "tier": "S",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2023,
      "score": 84,
      "comment": "Unique idea with excellent minimalistic execution. Short to beat.",
      "igdb_id": 7205,
      "rawg_id": "superhot",
    },
    {
      "name": "Shotgun King: The Final Checkmate",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2023,
      "score": 69,
      "comment": "Just like chess, \nbut you only have a King. \nWith a shotgun.",
      "igdb_id": 196030,
      "rawg_id": 783865,
    },
    {
      "name": "Colt Canyon",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2021,
      "score": 66,
      "comment": "Satisfying Western 2D \npixel art rouglike shooter.",
      "igdb_id": 114074,
      "rawg_id": 284763,
    },
    {
      "name": "Forager",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2021,
      "score": 70,
      "comment": "TODO",
      "igdb_id": 25580,
      "rawg_id": "forager",
    },
    {
      "name": "This Is the Police 2",
      "tier": "A",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2021,
      "score": 76,
      "comment": "U r a sheriff of snowy remote town. XCOM like combat w/ resource management of cops in between. Put 40h in.",
      "igdb_id": 84486,
      "rawg_id": "this-is-the-police-2",
    },
    {
      "name": "Opus Magnum",
      "tier": "A",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2021,
      "score": 82,
      "comment": "I'm an alchemy machine programmer. As close to coding and debugging while still being a fun game.",
      "igdb_id": 74545,
      "rawg_id": 48897,
    },
    {
      "name": "Minit",
      "tier": "S",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2019,
      "score": 86,
      "comment": "U have a minit to live!\nInsane how much was squizzed out of this simple idea!",
      "igdb_id": 26970,
      "rawg_id": "minit",
    },
    {
      "name": "Ruiner",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2018,
      "score": 71,
      "comment": "Awesome twin-stick shooter, atmospheric cyberpunk with awesome art and soundtrack. It's also a Polish cyberpunk, before Cyberpunk :D",
      "igdb_id": 18857,
      "rawg_id": 10537,
    },
    {
      "name": "Mini Metro",
      "tier": "B",
      "category": "AAA",
      "platform": "Android",
      "played_year": 2019,
      "score": 70,
      "comment": "Creative miminalistic puzzle game.",
      "igdb_id": 7767,
      "rawg_id": "mini-metro",
    },
    {
      "name": "Hearthstone",
      "tier": "A",
      "category": "AAA",
      "platform": "Android",
      "played_year": 2019,
      "score": 78,
      "comment": "Ma fav tavern.",
      "igdb_id": 18857,
      "rawg_id": "hearthstone",
    },
    {
      "name": "Steep",
      "tier": "A",
      "category": "AAA",
      "platform": "PlayStation 4",
      "played_year": 2019,
      "score": 83,
      "comment": "Almost meditative, satysfing locomotion.",
      "igdb_id": 19554,
      "rawg_id": "steep",
    },
    {
      "name": "Trackmania Turbo",
      "tier": "S",
      "category": "AAA",
      "platform": "PlayStation 4",
      "played_year": 2018,
      "score": 89,
      "comment": "Kept playing it for years. One of a kind arcade racing. Addictive rinse and repeat gameplay.",
      "igdb_id": 11172,
      "rawg_id": "trackmania-turbo",
    },
    {
      "name": "RiME",
      "tier": "B",
      "category": "Indie",
      "platform": "PlayStation 4",
      "played_year": 2018,
      "score": 69,
      "comment": "Heartwarming adventure with Journey/The Witness-like visuals that just suck you in. No HUD! But the puzzles are pretty shallow and it's more about exeriencing the art of it.",
      "igdb_id": 7621,
      "rawg_id": "rime",
    },
    {
      "name": "Rayman Origins",
      "tier": "S",
      "category": "AAA",
      "platform": "Xbox 360",
      "played_year": 2016,
      "score": 88,
      "comment": "The fast-pasted platforming with unique charming art style. My favorite Rayman game for sure!",
      "igdb_id": 981,
      "rawg_id": "rayman-origins",
    },
    {
      "name": "Chivalry: Medieval Warfare",
      "tier": "B",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2013,
      "score": 70,
      "comment": "Unusual combat mechanics for first-person multiplayer.",
      "igdb_id": 2358,
      "rawg_id": "chivalry-medieval-warfare",
    },
    {
      "name": "Battlefield 3",
      "tier": "S",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2013,
      "score": 88,
      "comment": "Destruction beyond imaginable for it's time! Was forced to register an Origin account.",
      "igdb_id": 343,
      "rawg_id": "battlefield-3",
    },
    {
      "name": "Tomb Raider",
      "tier": "A",
      "category": "AAA",
      "platform": "Xbox 360",
      "played_year": 2013,
      "score": 80,
      "comment": "Big fan of the reboot. Lara's <a href=\"${lara_radio_climb}\" target=\"_blank\">climb of the old radio tower scene</a> was so well directed. Big inspiration for cinematographic interactive levels in general.",
      "igdb_id": 1164,
      "rawg_id": "tomb-raider",
    },
    {
      "name": "Dante's Inferno",
      "tier": "A",
      "category": "AAA",
      "platform": "Xbox 360",
      "played_year": 2013,
      "score": 76,
      "comment": "God of War clone that lived up to the original. Enemy deisgn is next level is whole hell's-horror aethtetic stood out so much.",
      "igdb_id": 6958,
      "rawg_id": "dantes-inferno",
    },
    {
      "name": "Guitar Hero World Tour",
      "tier": "A",
      "category": "AAA",
      "platform": "Xbox 360",
      "played_year": 2013,
      "score": 81,
      "comment": "Remember buying it with money I got from my copywriting gigs.",
      "igdb_id": 2669,
      "rawg_id": "guitar-hero-world-tour",
    },
    {
      "name": "Guitar Hero: Metallica",
      "tier": "A",
      "category": "AAA",
      "platform": "Xbox 360",
      "played_year": 2013,
      "score": 82,
      "comment": "Ultimate karaoke experience with guitar and mic controllers!",
      "igdb_id": 2674,
      "rawg_id": "guitar-hero-metallica",
    },
    {
      "name": "Forza Horizon",
      "tier": "SS",
      "category": "AAA",
      "platform": "Xbox 360",
      "played_year": 2013,
      "score": 91,
      "comment": "My favourite racing game. The <a href=\"${ForzaHorizon_playlsit_url}\" target=\"_blank\">soundtrack</a> was insane, discovered <a href=\"${chaos_mark_cinematic}\" target=\"_blank\">Arctic Monkeys</a> in it. Open world street racing festival set in Colorado. It was magnificent",
      "igdb_id": 3047,
      "rawg_id": "forza-horizon",
    },
    {
      "name": "Borderlands 2",
      "tier": "A",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2012,
      "score": 83,
      "comment": "First game where PC “physical copy” contained NO real game data! There was just a code and I needed to wait for the whole thing to download from Steam for a few hours! One of the best coop experiences I had!",
      "igdb_id": 1011,
      "rawg_id": "borderlands-2",
    },
    {
      "name": "The Walking Dead: Season 1",
      "tier": "SS",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2012,
      "score": 91,
      "comment": "Played it as the episodes came out. A fantastic, moving story I wish I could forget just to experience again.",
      "igdb_id": 1871,
      "rawg_id": "the-walking-dead",
    },
    {
      "name": "DmC: Devil May Cry",
      "tier": "S",
      "category": "AAA",
      "platform": "Xbox 360",
      "played_year": 2013,
      "score": 87,
      "comment": "Loved the reimagination of Dante, cinematography, use of fonts and effects. Was 10/10 for me, not mentioning <a href=\"${dmc_combichrist}\" target=\"_blank\">Combichrist soundtrack</a>! Wish they went with this version of Date forward.",
      "igdb_id": 1254,
      "rawg_id": "dmc",
    },
    {
      "name": "Max Payne 3",
      "tier": "SS",
      "category": "",
      "platform": "PC",
      "played_year": 2012,
      "score": 97,
      "comment": "Neo-noir story + documentary style cinematography set in Brazil. One of the best-feeling controls in shooter game. Enormous inspiration for me gameplay-wise. No loading screens across gameplay and cutscenes  Took me a few days to download it on release!",
      "igdb_id": 960,
      "rawg_id": "max-payne-3"
    },
    {
      "name": "The Darkness II",
      "tier": "S",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2012,
      "score": 82,
      "comment": "Loved the aesthetics of it and gore graphic noir art style.",
      "igdb_id": 544,
      "rawg_id": "the-darkness-ii",
    },
    {
      "name": "Portal 2",
      "tier": "SSS",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2011,
      "score": 98,
      "comment": "M A S T E R P I E C E",
      "igdb_id": 72,
      "rawg_id": "portal-2",
    },
    {
      "name": "Wormix",
      "tier": "D",
      "category": "",
      "platform": "Browser",
      "played_year": 2011,
      "score": 61,
      "comment": "PvP browser clone of Worms, was pretty popular at the time(20 million players). Pay-to-Win was added at some point:/ RIP browser games.",
      "igdb_id": 315030,
      "rawg_id": "wormix",
    },
    {
      "name": "Tom Clancy's Splinter Cell: Essentials",
      "tier": "D",
      "category": "",
      "platform": "PSP",
      "played_year": 2010,
      "score": 57,
      "comment": "<a href=\"${psp_splinter_cell_stealth}\" target=\"_blank\">\"Peak\" stealth...</a>. Remember this game being way to dark, gray and hard to navigate :/",
      "igdb_id": 22632,
      "rawg_id": "tom-clancys-splinter-cell-essentials",
    },
    {
      "name": "Patapon 3",
      "tier": "A",
      "category": "",
      "platform": "PSP",
      "played_year": 2011,
      "score": 77,
      "comment": "Great rythm game, playing coop locally on PSP (PSP had its own wireless protocol!) was so much fun. Used to store cash in the Patapon's game case :D",
      "igdb_id": 21911,
      "rawg_id": "patapon-3",
    },
    {
      "name": "LittleBig Planet",
      "tier": "SS",
      "category": "",
      "platform": "PSP",
      "played_year": 2010,
      "score": 91,
      "comment": "The best PSP game I played, amount of user created levels were insane!",
      "igdb_id": 18373,
      "rawg_id": "littlebigplanet",
    },
    {
      "name": "Ace Combat X: Skies of Deception",
      "tier": "C",
      "category": "",
      "platform": "PSP",
      "played_year": 2010,
      "score": 61,
      "comment": "First game I played on my PSP-3000. Not the biggest fan though",
      "igdb_id": 14755,
      "rawg_id": "ace-combat-x-skies-of-deception",
    },
    {
      "name": "Naruto Shippuden: Ultimate Ninja 4",
      "tier": "A",
      "category": "",
      "platform": "PlayStation 2",
      "played_year": 2009,
      "score": 78,
      "comment": "Crazy that they released both Ultimate Ninja 4 and 5 the same year just because CyberConnect2 was rushing to close out PS2 development.\
      By 2007, PS3 had already launched in Japan (late 2006), so PS2 games were nearing the end of their commercial window. Poor devs.",
      "igdb_id": 19623,
      "rawg_id": "naruto-shippuden-ultimate-ninja-4",
    },
    {
      "name": "Naruto Shippuden: Ultimate Ninja 5",
      "tier": "A",
      "category": "",
      "platform": "PlayStation 2",
      "played_year": 2009,
      "score": 82,
      "comment": "My favorite 2D fighting of that time. Japan and Europe only release, suck it North America.",
      "igdb_id": 25112,
      "rawg_id": "naruto-shippuden-ultimate-ninja-5",
    },
    {
      "name": "Surf's Up",
      "tier": "B",
      "category": "",
      "platform": "PlayStation 2",
      "played_year": 2009,
      "score": 65,
      "comment": "Cozy surf-racing game",
      "igdb_id": 4191,
      "rawg_id": 25144,
    },
    {
      "name": "Grand Theft Auto IV",
      "tier": "SS",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2009,
      "score": 92,
      "comment": "Euphoria physics",
      "igdb_id": 731,
      "rawg_id": "grand-theft-auto-iv",
    },
    {
      "name": "Open Season",
      "tier": "C",
      "category": "",
      "platform": "PC",
      "played_year": 2007,
      "score": 62,
      "comment": "Remember it being extremly fun. Main gameplay is STEALTHing as a bear + bunch of well polished mini-games.",
      "igdb_id": 4055,
      "rawg_id": "open-season"
    },
    {
      "name": "Free Running",
      "tier": "B",
      "category": "",
      "platform": "PlayStation 2",
      "played_year": 2009,
      "score": 68,
      "comment": "Like Tony Hawk, but parkour. Same studio as Sniper Elite.",
      "igdb_id": 4873,
      "rawg_id": "free-running"
    },
    {
      "name": "LEGO Indiana Jones: The Original Adventures",
      "tier": "B",
      "category": "AAA",
      "platform": "PlayStation 2",
      "played_year": 2008,
      "score": 71,
      "comment": "First game I played on my PS2. 10th birthday present 🎂",
      "igdb_id": 189,
      "rawg_id": "lego-indiana-jones"
    },
    {
      "name": "Gravity Defied",
      "tier": "S",
      "category": "",
      "platform": "Sony Ericsson",
      "played_year": 2007,
      "score": 85,
      "comment": "This game was insanely hard. Every class break turned into a competition to beat the fastest run.",
      "igdb_id": 151054,
      "rawg_id": "gravity-defied-trial-racing"
    },
    {
      "name": "Heroes of Might and Magic 3",
      "tier": "SS",
      "category": "",
      "platform": "PC",
      "played_year": 2005,
      "score": 89,
      "comment": "Spent dozens of hours playing local multiplayer, looking away when it's not my turn 😋",
      "igdb_id": 51820,
      "rawg_id": 22685
    },
    {
      "name": "Pocket Tanks",
      "tier": "C",
      "category": "",
      "platform": "PC",
      "played_year": 2005,
      "score": 70,
      "comment": "1v1 `Worms`-like duel game. According to wikipedia: `The game is still being updated as of July 2025.` wtf",
      "igdb_id": 72176,
      "rawg_id": 76746
    },
    {
      "name": "Warhammer: Mark of Chaos",
      "tier": "A",
      "category": "",
      "platform": "PC",
      "played_year": 2007,
      "score": 83,
      "comment": "I remember it being super engaging and hard. The <a href=\"${chaos_mark_cinematic}\" target=\"_blank\">cinematic</a> looks insane event today!",
      "igdb_id": 7241,
      "rawg_id": "warhammer-mark-of-chaos"
    },
    {
      "name": "Spider-Man: Friend or Foe",
      "tier": "A",
      "category": "",
      "platform": "PlayStation 2",
      "played_year": 2007,
      "score": 90,
      "comment": "TODO:",
      "igdb_id": 5180,
      "rawg_id": "spider-man-friend-or-foe"
    },
    {
      "name": "Prince of Persia: Warrior Within",
      "tier": "S",
      "category": "",
      "platform": "PC",
      "played_year": 2007,
      "score": 91,
      "comment": "TODO",
      "igdb_id": 837,
      "rawg_id": "prince-of-persia-warrior-within"
    },
    {
      "name": "Prince of Persia: The Two Thrones",
      "tier": "SS",
      "category": "",
      "platform": "PC",
      "played_year": 2006,
      "score": 93,
      "comment": "First PoP game I played, and it was magnificent. Lifelong fan now!",
      "igdb_id": 2437,
      "rawg_id": "prince-of-persia-the-two-thrones"
    },
    {
      "name": "Prince of Persia: The Sands of Time",
      "tier": "A",
      "category": "",
      "platform": "PC",
      "played_year": 2006,
      "score": 83,
      "comment": "TODO",
      "igdb_id": 836,
      "rawg_id": "prince-of-persia-the-sands-of-time"
    },
    {
      "name": "Rayman Raving Rabbids",
      "tier": "B",
      "category": "",
      "platform": "PC",
      "played_year": 2006,
      "score": 73,
      "comment": "My intro to Ubisoft games, also first game ever to feature the iconic Rabbids!",
      "igdb_id": 2277,
      "rawg_id": "rayman-raving-rabbids"
    },
    {
      "name": "Need for Speed: Underground 2",
      "tier": "S",
      "category": "",
      "platform": "PC",
      "played_year": 2006,
      "score": 82,
      "comment": "Motion blur is the coolest thing ever",
      "igdb_id": 242997,
      "rawg_id": 53446
    },
    {
      "name": "Scooby-Doo! Two: Monsters Unleashed",
      "tier": "C",
      "category": "",
      "platform": "PC",
      "played_year": 2006,
      "score": 77,
      "comment": "First game I played on my first PC 🎂",
      "igdb_id": 49184,
      "rawg_id": 35821
    }
  ];