  const gameMasterList = [
    {
      "name": "Dota 2",
      "tier": "SSS",
      "category": "",
      "platform": "PC",
      "played_year": 2012,
      "score": 99,
      "comment": "No comments.",
      "igdb_id": 2963,
      "rawg_id": 10213,
    },
    {
      "name": "Hollow Knight: Silksong",
      "tier": "SSS",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 98,
      "comment": `Perfect sequel for
      the best metroidvania,
      that excels in every aspect.`,
      "igdb_id": 115289,
      "rawg_id": 292844,
    },
    {
      "name": "Hollow Knight",
      "tier": "SSS",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2019,
      "score": 96,
      "comment": "Best metroidvania of it's time with combat depth and vast engaging world.",
      "igdb_id": 365702,
      "rawg_id": 9767,
    },
    {
      "name": "Disc Room",
      "tier": "A",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 75,
      "comment": "Fast gameplay loop. Hardcode 2D micro-skill-demending game aboud dodging DISCS.",
      "igdb_id": 131614,
      "rawg_id": 513878,
    },
    {
      "name": "The Messenger",
      "tier": "A",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 80,
      "comment": "Clever commentary on a genre, disguised as a classic action platformer. Medium-challenge.",
      "igdb_id": 71628,
      "rawg_id": 302239,
    },
    {
      "name": "Level Devil",
      "tier": "S",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 90,
      "comment": "So creative with so little. Game messes with your expectations.",
      "igdb_id": 279687,
      "rawg_id": 1000161,
    },
    {
      "name": "Haste",
      "tier": "A",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 76,
      "comment": "3D-runner with unique satisfying locomotion mechanics and very polished animations. Not a fun of the plot though.",
      "igdb_id": 228918,
      "rawg_id": 719612,
    },
    {
      "name": "King is Watching",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 74,
      "comment": "3D-runner with unique satisfying locomotion mechanics and very polished animations. Not a fun of the plot though.",
      "igdb_id": 282826,
      "rawg_id": 1007234,
    },
    {
      "name": "Bridge Constructor Portal",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2025,
      "score": 68,
      "comment": "Satisfying portal-themed puzzles, Portal humor included",
      "igdb_id": 76770,
      "rawg_id": 50675,
    },
    {
      "name": "Detroit: Become Human",
      "tier": "SS",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2025,
      "score": 90,
      "comment": "As good as an interactive-movie kinda game can go. True story branching, main character can die midway through and the game goes on. Played as a local coop.",
      "igdb_id": 14362,
      "rawg_id": 29177,
    },
    {
      "name": "Lara Croft GO",
      "tier": "A",
      "category": "",
      "platform": "PC",
      "played_year": 2025,
      "score": 74,
      "comment": "Classic turn base 2D puzzle, great twists on mechanics, in-depth exploration of each mechanic and how it overlaps with others. Constantly gives you an a-ha moment.",
      "igdb_id": 11592,
      "rawg_id": 700,
    },
    {
      "name": "Shotgun King: The Final Checkmate",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2023,
      "score": 69,
      "comment": "Just like chess, \nbut you only have a King. \nWith a shotgun.",
      "igdb_id": 196030,
      "rawg_id": 783865,
    },
    {
      "name": "Colt Canyon",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2021,
      "score": 66,
      "comment": "Satisfying Western 2D \npixel art rouglike shooter.",
      "igdb_id": 114074,
      "rawg_id": 284763,
    },
    {
      "name": "Opus Magnum",
      "tier": "A",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2021,
      "score": 82,
      "comment": "I'm an alchemy machine programmer. As close to coding and debugging while still being a fun game.",
      "igdb_id": 74545,
      "rawg_id": 48897,
    },
    {
      "name": "Minit",
      "tier": "S",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2019,
      "score": 66,
      "comment": "U have a minit to live!\nInsane how much was squizzed out of this simple idea!",
      "igdb_id": 26970,
      "rawg_id": minit,
    },
    {
      "name": "Ruiner",
      "tier": "B",
      "category": "Indie",
      "platform": "PC",
      "played_year": 2018,
      "score": 71,
      "comment": "Awesome twin-stick shooter, atmospheric cyberpunk with awesome art and soundtrack. It's also a Polish cyberpunk, before Cyberpunk :D",
      "igdb_id": 18857,
      "rawg_id": 10537,
    },
    {
      "name": "The Darkness II",
      "tier": "S",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2012,
      "score": 82,
      "comment": "Loved the aesthetics of it and gore graphic noir art style.",
      "igdb_id": 544,
      "rawg_id": the-darkness-ii,
    },
    {
      "name": "Surf's Up",
      "tier": "B",
      "category": "",
      "platform": "PlayStation 2",
      "played_year": 2009,
      "score": 65,
      "comment": "Cozy surf-racing game",
      "igdb_id": 4191,
      "rawg_id": 25144,
    },
    {
      "name": "Grand Theft Auto IV",
      "tier": "SS",
      "category": "AAA",
      "platform": "PC",
      "played_year": 2009,
      "score": 92,
      "comment": "Euphoria physics",
      "igdb_id": 731,
      "rawg_id": "grand-theft-auto-iv",
    },
    {
      "name": "Heroes of Might and Magic 3",
      "tier": "SS",
      "category": "",
      "platform": "PC",
      "played_year": 2005,
      "score": 89,
      "comment": "Spent dozens of hours playing local multiplayer, looking away when it's not my turn 😋",
      "igdb_id": 51820,
      "rawg_id": 22685
    },
    {
      "name": "Pocket Tanks",
      "tier": "C",
      "category": "",
      "platform": "PC",
      "played_year": 2005,
      "score": 70,
      "comment": "1v1 `Worms`-like duel game. According to wikipedia: `The game is still being updated as of July 2025.` wtf",
      "igdb_id": 72176,
      "rawg_id": 76746
    },
    {
      "name": "Need for Speed: Underground 2",
      "tier": "S",
      "category": "",
      "platform": "PC",
      "played_year": 2006,
      "score": 82,
      "comment": "Motion blur is the coolest thing ever",
      "igdb_id": 242997,
      "rawg_id": 53446
    },
    {
      "name": "Scooby-Doo! Two: Monsters Unleashed",
      "tier": "C",
      "category": "",
      "platform": "PC",
      "played_year": 2006,
      "score": 77,
      "comment": "First game I played on my first PC 🎂",
      "igdb_id": 49184,
      "rawg_id": 35821
    }
  ];